version: "3.6"

services:
  bare: &bare
    image: node:10
    working_dir: /app/
    command: yarn dev
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    environment:
      APP_VERSION: 0.1.0-snapshot
      ENVIRONMENT_NAME: default
      PORT: 5000

  full:
    <<: *bare
    ports:
      - 5000:5000

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
