{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "demo-app.serviceAccountName" . }}
  labels:
{{ include "demo-app.labels" . | indent 4 }}
{{- end -}}
